---
- hosts: 127.0.0.1
  connection: local
  remote_user: root
  
  vars:
  #config your 5G core running server IP
    ip_address: 192.168.80.145  

  tasks:
    - name  : Update APT
      shell :  |
            sudo apt update  
             
    - name : Install software-properties-common
      apt  :
            name: ['software-properties-common']

    - name : Add Open5GS apt repository
      shell :  |
            sudo add-apt-repository ppa:open5gs/latest
            
    - name  : Update APT
      shell :  |
            sudo apt update

    - name : Install Open5GS
      apt  :
            name: ['open5gs']
            
    - name : Install Open5GS
      apt  :
            name: ['vim']
            
    - name  : Build amf config file
      copy  :
        dest: "/etc/open5gs/amf.yaml"
        content: |
          logger:
              file: /var/log/open5gs/amf.log
          amf:
              sbi:
                - addr: 127.0.0.5
                  port: 7777
              ngap:
                - addr: {{ip_address}}
              guami:
                - plmn_id:
                    mcc: 901
                    mnc: 70
                  amf_id:
                    region: 2
                    set: 1
              tai:
                - plmn_id:
                    mcc: 901
                    mnc: 70
                  tac: 1
              plmn_support:
                - plmn_id:
                    mcc: 901
                    mnc: 70
                  s_nssai:
                    - sst: 1
              security:
                  integrity_order : [ NIA2, NIA1, NIA0 ]
                  ciphering_order : [ NEA0, NEA1, NEA2 ]
              network_name:
                  full: Open5GS
              amf_name: open5gs-amf0
              
          nrf:
              sbi:
                - addr:
                  - 127.0.0.10
                  - ::1
              port: 7777

    - name  : Restart amf services
      shell :  |
            sudo systemctl restart open5gs-amfd 
            
    #- name  : Amf logs can be found in /var/log/open5gs/amf.log
    #  shell :  |
    #        sudo tail -f /var/log/open5gs/amf.log
    
             



  
