---
- hosts: server2
  connection: local
  remote_user: root
 
  vars:
  #config your UE and gnb running server IP
    ip_address: server2
  #config your path for installation
    BASE_DIR_INSTALL: '/home/jxy6184'
    
  tasks:            
     # install cmake
     # UERANSIM does not work with the apt version of cmake, that's why we need to install snap and the snap version of cmake:
    - name  : Update APT
      shell :  |
            sudo apt update
            
    - name  : Upgrade APT
      shell :  |
            sudo apt upgrade
            
    - name  : Install make
      apt :  
            name: ['make'] 
    
    - name  : Install g++
      apt :  
            name: ['g++']
            
    - name  : Install libsctp-dev
      apt :  
            name: ['libsctp-dev']      

    - name  : Install lksctp-tools
      apt :  
            name: ['lksctp-tools'] 
            
    - name  : Install bison
      apt  :
            name: ['bison']

    - name  : Install flex
      apt  :
            name: ['flex']

    - name  : Install iproute2
      apt  :
            name: ['iproute2']

    - name  : Install iproute2-doc
      apt  :
            name: ['iproute2-doc']

    - name  : Install net-tools
      apt   :
            name: ['net-tools']

    - name  : Install cmake
      shell :  |
            sudo snap install cmake --classic

    - name  : Install git
      apt   :
            name: ['git']

    - name  : Install ueransim
      shell :
        cmd : git clone https://github.com/aligungr/UERANSIM
        chdir: "{{BASE_DIR_INSTALL}}"

    - name  : Make UERANSIM
      shell :
        cmd : make
        chdir: "{{BASE_DIR_INSTALL}}/UERANSIM"

            


  

