---
- hosts: 127.0.0.1
  connection: local
  remote_user: root
  
  vars:
  #config your 5G core running server IP
    ip_address: 192.168.80.145  
  #config your path for installation
    BASE_DIR_INSTALL: '/home/jxy6184'
    
  tasks:
    - name  : Update APT
      shell :  |
            sudo apt update  
             
    - name : Install software-properties-common
      apt  :
            name: ['software-properties-common']

    - name : Add Open5GS apt repository
      shell :  |
            sudo add-apt-repository ppa:open5gs/latest
            
    - name  : Update APT
      shell :  |
            sudo apt update

    - name : Install Open5GS
      apt  :
            name: ['open5gs']
            
    - name : Install Open5GS
      apt  :
            name: ['vim']
            
    - name  : Build amf config file
      copy  :
        dest: "/etc/open5gs/amf.yaml"
        content: |
          logger:
              file: /var/log/open5gs/amf.log
          amf:
              sbi:
                - addr: 127.0.0.5
                  port: 7777
              ngap:
                - addr: {{ip_address}}
              guami:
                - plmn_id:
                    mcc: 901
                    mnc: 70
                  amf_id:
                    region: 2
                    set: 1
              tai:
                - plmn_id:
                    mcc: 901
                    mnc: 70
                  tac: 1
              plmn_support:
                - plmn_id:
                    mcc: 901
                    mnc: 70
                  s_nssai:
                    - sst: 1
              security:
                  integrity_order : [ NIA2, NIA1, NIA0 ]
                  ciphering_order : [ NEA0, NEA1, NEA2 ]
              network_name:
                  full: Open5GS
              amf_name: open5gs-amf0
              
          nrf:
              sbi:
                - addr:
                  - 127.0.0.10
                  - ::1
              port: 7777

    - name  : Restart amf services
      shell :  |
            sudo systemctl restart open5gs-amfd 
            
    #- name  : Amf logs can be found in /var/log/open5gs/amf.log
    #  shell :  |
    #        sudo tail -f /var/log/open5gs/amf.log
    
    - name  : Build upf config file
      copy  :
        dest: "/etc/open5gs/upf.yaml"
        content: |
          logger:
              file: /var/log/open5gs/upf.log
          upf:
              pfcp:
                - addr: 127.0.0.7
              gtpu:
                - addr: {{ip_address}}
              subnet:
                - addr: 10.45.0.1/16
                - addr: 2001:230:cafe::1/48


    - name  : Restart amf services
      shell :  |
            sudo systemctl restart open5gs-upfd 
            
    - name  : Nat port forwarding(1/4)
      shell :  |
            sudo sysctl -w net.ipv4.ip_forward=1
            
    - name  : Nat port forwarding(2/4)
      shell :  |                 
            sudo iptables -t nat -A POSTROUTING -o ens33 -j MASQUERADE
            
    - name  : Nat port forwarding(3/4)
      shell :  |                   
            sudo systemctl stop ufw
            
    - name  : Nat port forwarding(4/4)
      shell :  |                           
            sudo iptables -I FORWARD 1 -j ACCEPT

    # install nodejs
    - name  : Update APT
      shell :  |
            sudo apt update

    - name : Install curl
      apt  :
            name: ['curl']
    
    - name: Prepare for nodejs
      shell:  |
            curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -

    - name : Install nodejs
      apt  :
            name: ['nodejs']
    
    - name : Clone webui
      shell:  |
            git clone https://github.com/open5gs/open5gs.git

    - name : Install npm
      shell:
         cmd: npm install
         chdir: "{{BASE_DIR_INSTALL}}/6184_5G_ansible_deployment/Open5GS_and_UERANSIM_deployment/open5gs/webui"

    - name : Run open5gs
      shell:
         cmd: npm run dev --host 0.0.0.0
         chdir: "{{BASE_DIR_INSTALL}}/6184_5G_ansible_deployment/Open5GS_and_UERANSIM_deployment/open5gs/webui"


  

