---
- hosts: server2
  remote_user: root
 
  vars:
  #config your 5G core running server IP
    ip1_address: 192.168.80.145  
  #config your UE and gnb running server IP
    ip2_address: 192.168.80.148  
  #config your path for installation
    BASE_DIR_INSTALL: '/home/jxy6184'
    
  tasks:            
     # install cmake
     # UERANSIM does not work with the apt version of cmake, that's why we need to install snap and the snap version of cmake:
    - name  : Update APT
      shell :  |
            sudo apt update
            
    - name  : Upgrade APT
      shell :  |
            sudo apt upgrade
            
    - name  : Install make
      apt :  
            name: ['make'] 
    
    - name  : Install g++
      apt :  
            name: ['g++']
            
    - name  : Install libsctp-dev
      apt :  
            name: ['libsctp-dev']      

    - name  : Install lksctp-tools
      apt :  
            name: ['lksctp-tools'] 
            
    - name  : Install bison
      apt  :
            name: ['bison']

    - name  : Install flex
      apt  :
            name: ['flex']

    - name  : Install iproute2
      apt  :
            name: ['iproute2']

    - name  : Install iproute2-doc
      apt  :
            name: ['iproute2-doc']

    - name  : Install net-tools
      apt   :
            name: ['net-tools']

    - name  : Install cmake
      shell :  |
            sudo snap install cmake --classic

    - name  : Install git
      apt   :
            name: ['git']

    - name  : Install ueransim
      shell :
        cmd : git clone https://github.com/aligungr/UERANSIM
        chdir: "{{BASE_DIR_INSTALL}}"

    - name  : Make UERANSIM
      shell :
        cmd : make
        chdir: "{{BASE_DIR_INSTALL}}/UERANSIM"
        
    - name  : Build gnb config file
      copy  :
        dest: "{{BASE_DIR_INSTALL}}/UERANSIM/config/open5gs-gnb.yaml"
        content: |
          mcc: '901'          # Mobile Country Code value
          mnc: '70'           # Mobile Network Code value (2 or 3 digits)

          nci: '0x000000010'  # NR Cell Identity (36-bit)
          idLength: 32        # NR gNB ID length in bits [22...32]
          tac: 1              # Tracking Area Code

          linkIp: {{ip2_address}}   # gNB's local IP address for Radio Link Simulation (Usually same with local IP)
          ngapIp: {{ip2_address}}   # gNB's local IP address for N2 Interface (Usually same with local IP)
          gtpIp: {{ip2_address}}    # gNB's local IP address for N3 Interface (Usually same with local IP)

          # List of AMF address information
          amfConfigs:
            - address: {{ip1_address}}
              port: 38412

          # List of supported S-NSSAIs by this gNB
          slices:
            - sst: 1

    - name  : Build UE config file
      copy  :
        dest: "{{BASE_DIR_INSTALL}}/UERANSIM/config/open5gs-ue.yaml"
        content: |
          # IMSI number of the UE. IMSI = [MCC|MNC|MSISDN] (In total 15 digits)
          supi: 'imsi-901700000000001'
          # Mobile Country Code value of HPLMN
          mcc: '901'
          # Mobile Network Code value of HPLMN (2 or 3 digits)
          mnc: '70'

          # Permanent subscription key
          key: '465B5CE8B199B49FAA5F0A2EE238A6BC'
          # Operator code (OP or OPC) of the UE
          op: 'E8ED289DEBA952E4283B54E88E6183CA'
          # This value specifies the OP type and it can be either 'OP' or 'OPC'
          opType: 'OPC'
          # Authentication Management Field (AMF) value
          amf: '8000'
          # IMEI number of the device. It is used if no SUPI is provided
          imei: '356938035643803'
          # IMEISV number of the device. It is used if no SUPI and IMEI is provided
          imeiSv: '4370816125816151'

          # List of gNB IP addresses for Radio Link Simulation
          gnbSearchList:
            - {{ip2_address}}
         
          # UAC Access Identities Configuration
          uacAic:
            mps: false
            mcs: false

          # UAC Access Control Class
          uacAcc:
            normalClass: 0
            class11: false
            class12: false
            class13: false
            class14: false
            class15: false

          # Initial PDU sessions to be established
          sessions:
            - type: 'IPv4'
              apn: 'internet'
              slice:
                sst: 1

          # Configured NSSAI for this UE by HPLMN
          configured-nssai:
            - sst: 1

          # Default Configured NSSAI for this UE
          default-nssai:
            - sst: 1
              sd: 1

          # Supported integrity algorithms by this UE
          integrity:
            IA1: true
            IA2: true
            IA3: true

          # Supported encryption algorithms by this UE
          ciphering:
            EA1: true
            EA2: true
            EA3: true

          # Integrity protection maximum data rate for user plane
          integrityMaxRate:
            uplink: 'full'
            downlink: 'full'




            


  

